### ISSUE TITLE
Create a 'drush' task type

### ISSUE THREAD

**Issue by claudiu-cristea** [claudiu-cristea/yaml-drush-commands#1]
It should be possible to add this task:

```yaml
- task: drush
  params:
      command: 'site:install'
      arguments:
        - umami
      options:
        yes: ~
```
