### ISSUE TITLE
Allow using vars in YAML

### ISSUE THREAD

**Issue by claudiu-cristea** [claudiu-cristea/yaml-drush-commands#2]
Should be able to do this:

```yaml
config:
   foo: Bar
commands:
  my:cmd:
    tasks:
      - task: exec
        params:
          exec: echo "${foo}"
```

Somehow, the `config` should be added and resolved to Drush configuration. Is this possible?
